### ISSUE TITLE
Missing instructions on dataset setup for Pandas course

### ISSUE THREAD

**Issue by dzieciou** [Kaggle/learntools#134]
1. I did `git clone https://github.com/Kaggle/learntools.git`.
2. I followed instructions for Panda Course running the first example and got the following error:

```
D:\Projects-intellij\machine-learning-course\kaggle\learntools>python ex1.py
Traceback (most recent call last):
  File "ex1.py", line 4, in <module>
    from learntools.pandas.creating_reading_and_writing import *
  File "D:\Projects-intellij\machine-learning-course\kaggle\learntools\learntools\pandas\creating_reading_and_writing.py", line 49, in <module>
    class ReadWineCsv(EqualityCheckProblem):
  File "D:\Projects-intellij\machine-learning-course\kaggle\learntools\learntools\pandas\creating_reading_and_writing.py", line 54, in ReadWineCsv
    _expected = pd.read_csv('../input/wine-reviews/winemag-data_first150k.csv', index_col=0)
  File "C:\Users\OEM\Miniconda3\lib\site-packages\pandas\io\parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\OEM\Miniconda3\lib\site-packages\pandas\io\parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\OEM\Miniconda3\lib\site-packages\pandas\io\parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "C:\Users\OEM\Miniconda3\lib\site-packages\pandas\io\parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\OEM\Miniconda3\lib\site-packages\pandas\io\parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 387, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 705, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'../input/wine-reviews/winemag-data_first150k.csv' does not exist: b'../input/wine-reviews/winemag-data_first150k.csv'

```

Where can I find instructions on how to setup datasets for the course?

**Comment by dansbecker** [comment]
These courses are available for free at [kaggle.com/learn/pandas](kaggle.com/learn/pandas) but we don't support pulling everything onto your local computer to run it there.

We aren't opposed to you doing this, but it will be a decent amount of work, and isn't a priority for us to support it in the near future.
